run_tests:
  image: python:3.10-slim-buster
  before_script:
    - apt-get update && apt-get install -y postgresql
    - apt-get install -y python-psycopg2
    - apt-get install -y libpq-dev
    - pip install psycopg2-binary
    - pip install -r requirements.txt
  script:
    - python3 manage.py test
  