# Generated by Django 4.1 on 2022-08-21 18:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone_no'),
    ]

    operations = [
        
    ]
