# Generated by Django 4.1 on 2022-08-21 18:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userphonenumber_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphonenumber',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
