# Generated by Django 4.1 on 2022-08-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userphonenumber_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='core.userphonenumber'),
        ),
    ]
