# Generated by Django 4.1 on 2022-08-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
