# Generated by Django 4.1 on 2022-08-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userphonenumber_alter_user_phone_no'),
        ('core', '0009_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoneNumber',
        ),
    ]
