# Generated by Django 4.1 on 2022-08-23 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_delete_userphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('duration', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('execute_datetime', models.DateTimeField()),
                ('reservatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='core.sessionroom')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
