# Generated by Django 4.1 on 2022-08-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reserve_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionroom',
            old_name='have_cooler',
            new_name='has_cooler',
        ),
        migrations.RenameField(
            model_name='sessionroom',
            old_name='have_heater',
            new_name='has_heater',
        ),
    ]
