# Generated by Django 4.1 on 2022-08-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_have_cooler_sessionroom_has_cooler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionroom',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
