# Generated by Django 4.1 on 2022-08-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sessionroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionroom',
            name='has_projector',
            field=models.BooleanField(default=False),
        ),
    ]
