# Generated by Django 4.1 on 2022-08-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sessionroom_has_cooler_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='RoomInfo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='core.sessionroom')),
        #     ],
        # ),
    ]
