# Generated by Django 4.1 on 2022-08-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_roominfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='ikey',
            field=models.CharField(default='گرمایش', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roominfo',
            name='ivalue',
            field=models.CharField(default='دارد', max_length=50),
            preserve_default=False,
        ),
    ]
