# Generated by Django 4.1 on 2022-08-25 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_roominfo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
       
    ]
