# Generated by Django 4.1 on 2022-08-26 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reserve_end_datetime_reserve_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
