# Generated by Django 4.1 on 2022-08-26 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_reserve_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
