# Generated by Django 4.1 on 2022-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_reserve_duration'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reserve',
        #     name='departman',
        # ),
    ]
