# Generated by Django 4.1 on 2022-08-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_departman_department_and_more'),
        ('core', '0026_remove_reserve_departman'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='reserve',
        #     name='department',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='authentication.department'),
        # ),
    ]
