# Generated by Django 4.1 on 2022-08-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_reserve_department'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reserve',
        #     name='department',
        # ),
    ]
