# Generated by Django 4.1 on 2022-08-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_user_department'),
        ('core', '0028_remove_reserve_department'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='reserve',
        #     name='department',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='authentication.department'),
        # ),
    ]
