# Generated by Django 4.1 on 2022-08-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='authentication.userphonenumber'),
            preserve_default=False,
        ),
    ]
