# Generated by Django 4.1 on 2022-08-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userphonenumber_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='authentication.userphonenumber'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
