# Generated by Django 4.1 on 2022-08-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_no_alter_userphonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='authentication.userphonenumber'),
        ),
    ]
