# Generated by Django 4.1 on 2022-08-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_departman_alter_userphonenumber_country_code'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
