# Generated by Django 4.1 on 2022-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.CharField(default='demo', max_length=255),
        ),
    ]
