# Generated by Django 4.1 on 2022-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_user_phone_no'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Departman',
        #     new_name='Department',
        # ),
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='departman',
        #     new_name='department',
        # ),
    ]
