# Generated by Django 4.1 on 2022-08-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_departman_department_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='department',
        # ),
    ]
